name: Automate CI

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure pytest is included

      - name: Check installed packages
        run: pip list  # Debugging step to check installed dependencies

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings | tee test_output.log  # Run tests and log output

      - name: Upload Test Logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: test-logs
          path: test_output.log
